language: node_js
node_js:
  - 0.6
  - 0.8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./node_modules/.bin/site-manager test/site &
  - sleep 5
script: phantomjs test/qunit/run-qunit.js 'http://localhost:3000/test.html'